---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Create certs directory.
  file:
    path: "{{ kibana_certs_path }}"
    state: directory
    owner: root
    group: kibana
    mode: 0755

- name: Copy Elasticsearch CA certificates.
  copy:
    src: "{{ item }}"
    dest: "{{ kibana_certs_path }}/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ kibana_elasticsearch_ca_certificates }}"
  when: kibana_elasticsearch_ca_certificates | length > 0

- name: Copy Kibana configuration.
  template:
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
